packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  typescript: ^6.0.3
  "@types/node": ^24.9.2
  "drizzle-orm": ^0.45.2
  "drizzle-kit": ^0.31.10
  pg: ^8.23.0
  "@types/pg": ^8.23.1
  fastify: ^5.12.4
  zod: ^4.6.4
  "fastify-type-provider-zod": ^7.0.0
  "fastify-plugin": ^6.0.0

minimumReleaseAgeExclude:
  - zod@4.6.4
